---
# tasks file for ansible_ssh_hardening

- name: Install OpenSSH server
  apt:
    name:
      - openssh-server
    state: present
    update_cache: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Config fail2ban for ssh
  blockinfile:
    path: /etc/fail2ban/jail.local
    create: yes
    mode: 0644
    block: |
      [DEFAULT]
      bantime = 666
      
      [sshd]
      enabled = true
  notify:
    - Enable and restart fail2ban

- name: Permit ssh root access with key only
  replace:
    path: /etc/ssh/sshd_config
    regexp: '.?PermitRootLogin[ \t]+(?:yes\b|no\b)'
    replace: 'PermitRootLogin prohibit-password'
  notify:
    - Restart SSH

- name: Disable password authentication for SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '.?PasswordAuthentication[ \t]+(?:yes\b|no\b)'
    replace: 'PasswordAuthentication no'
  notify:
    - Restart SSH
