---
# handlers file for ansible-ssh

- name: Restart SSH
  systemd: 
    state: restarted
    name: sshd

- name: Restart ufw
  systemd: 
    state: restarted
    name: ufw
  
- name: Enable and restart fail2ban
  systemd: 
    enabled: yes
    state: restarted
    name: fail2ban
