---
# handlers file for ansible_ssh_hardening

- name: Restart SSH
  systemd: 
    state: restarted
    name: sshd

- name: Enable and restart fail2ban
  systemd: 
    enabled: yes
    state: restarted
    name: fail2ban
