---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: Include test vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  tasks:
    - name: Include role
      include_role: 
        name: ansible_ssh_hardening
