---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
        ansible-version:
          - 2.9
          - 3
          - 4
        python-version:
          - 3.8
          - 3.9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: pip3 install ansible==${{ matrix.ansible-version }}.* molecule[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}


