name: Molecule

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
        ansible-version:
          - 2.9
          - 3
          - 4
        python-version:
          - 3.8
          - 3.9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip3 install wheel
          pip3 install ansible==${{ matrix.ansible-version }}.* molecule[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
